services:
  mongodb:
    image: bitnami/mongodb:8.0.4
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    restart: always

  redis:
    image: redis:7.4-alpine
    container_name: redis
    ports:
      - '6379:6379'

  backend:
    container_name: url-shortener-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    build:
      context: ./
      dockerfile: ./apps/url-shortener/Dockerfile

  frontend:
    container_name: url-shortener-client
    restart: always
    ports:
      - '4200:80'
    depends_on:
      - backend
    build:
      context: ./
      dockerfile: ./apps/client/Dockerfile
